### ISSUE TITLE
not working in macos high sierra

### ISSUE THREAD

**Issue by mahwd** [munisisazade/docker-helper-commands#1]
<img width="770" alt="screen shot 2018-09-28 at 09 18 15" src="https://user-images.githubusercontent.com/25174247/46189393-76c6f700-c2ff-11e8-87a4-d9a66f07adeb.png">
The scripts are already in    _**~/.local/bin**_   but can't run command systemwide

**Comment by munisisazade** [comment]
This issue was fixed
